package com.springmvc.service;

import com.springmvc.pojo.Address;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AddressService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated
     */
    Address selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated
     */
    List<Address> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Address record);



    List<Address> getAllAddressByUid(Integer Uid);

    /**
     * 添加address
     * @param address
     */
    void addAddress(Address address);

    /**
     * 设置is_default
     * @param uid
     * @param id
     */
    void setDefault(Integer uid, Integer id);

    /**
     * 通过id查询Address信息,并返回
     * @param id
     * @return
     */
    Address getAddressById(Integer id);
    /**
     * 修改Address
     * @param address
     */
    void updateAddress(Address address);

    /**
     * 删除address记录
     * @param uid
     * @param id
     */
    void deleteAddress(Integer uid, Integer id);


}
