package com.springmvc.service;

import com.springmvc.pojo.Orders;

import java.util.List;

public interface OrdersService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    List<Orders> selectAll();



    List<Orders> selectOrdersByUserId(Integer userId);

    Orders selectOrdersByGoodId(Integer goodId);


    Double getSpendByUserId(Integer userId);

    Double getIncomeByUserId(Integer userId);
}
