package com.springmvc.service;

import com.springmvc.pojo.Wanted;

import java.util.List;

public interface WantedService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wanted
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wanted
     *
     * @mbggenerated
     */
    int insert(Wanted record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wanted
     *
     * @mbggenerated
     */
    Wanted selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wanted
     *
     * @mbggenerated
     */
    List<Wanted> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wanted
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Wanted record);

    Wanted selectWant(Integer uid, Integer gid);

    List<Wanted> selectWantByUserId(Integer uid);

    int deleteWantedByGoodsId(Integer gid);


}
