package com.springmvc.pojo;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.catelog_id
     *
     * @mbggenerated
     */
    private Integer catelogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbggenerated
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.real_price
     *
     * @mbggenerated
     */
    private Float realPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.start_time
     *
     * @mbggenerated
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.polish_time
     *
     * @mbggenerated
     */
    private String polishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.end_time
     *
     * @mbggenerated
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.commet_num
     *
     * @mbggenerated
     */
    private Integer commetNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.phone_number
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.qq_number
     *
     * @mbggenerated
     */
    private String qqNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.wx_number
     *
     * @mbggenerated
     */
    private String wxNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.good_city
     *
     * @mbggenerated
     */
    private String goodCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.good_buy_method
     *
     * @mbggenerated
     */
    private String goodBuyMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.good_address
     *
     * @mbggenerated
     */
    private String goodAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.viewCount
     *
     * @mbggenerated
     */
    private Integer viewcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.describle
     *
     * @mbggenerated
     */
    private String describle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.describle
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods.status
     *
     * @mbggenerated
     */
    public Goods(Integer id, Integer catelogId, Integer userId, String name, Float price, Float realPrice, String startTime, String polishTime, String endTime, Integer commetNum, String phoneNumber, String qqNumber, String wxNumber, String goodCity, String goodBuyMethod, String goodAddress, Integer viewcount, String describle,Byte status) {
        this.id = id;
        this.catelogId = catelogId;
        this.userId = userId;
        this.name = name;
        this.price = price;
        this.realPrice = realPrice;
        this.startTime = startTime;
        this.polishTime = polishTime;
        this.endTime = endTime;
        this.commetNum = commetNum;
        this.phoneNumber = phoneNumber;
        this.qqNumber = qqNumber;
        this.wxNumber = wxNumber;
        this.goodCity = goodCity;
        this.goodBuyMethod = goodBuyMethod;
        this.goodAddress = goodAddress;
        this.viewcount = viewcount;
        this.describle = describle;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated
     */
    public Goods() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.catelog_id
     *
     * @return the value of goods.catelog_id
     *
     * @mbggenerated
     */
    public Integer getCatelogId() {
        return catelogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.catelog_id
     *
     * @param catelogId the value for goods.catelog_id
     *
     * @mbggenerated
     */
    public void setCatelogId(Integer catelogId) {
        this.catelogId = catelogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.user_id
     *
     * @return the value of goods.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.user_id
     *
     * @param userId the value for goods.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbggenerated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbggenerated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.real_price
     *
     * @return the value of goods.real_price
     *
     * @mbggenerated
     */
    public Float getRealPrice() {
        return realPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.real_price
     *
     * @param realPrice the value for goods.real_price
     *
     * @mbggenerated
     */
    public void setRealPrice(Float realPrice) {
        this.realPrice = realPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.start_time
     *
     * @return the value of goods.start_time
     *
     * @mbggenerated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.start_time
     *
     * @param startTime the value for goods.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.polish_time
     *
     * @return the value of goods.polish_time
     *
     * @mbggenerated
     */
    public String getPolishTime() {
        return polishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.polish_time
     *
     * @param polishTime the value for goods.polish_time
     *
     * @mbggenerated
     */
    public void setPolishTime(String polishTime) {
        this.polishTime = polishTime == null ? null : polishTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.end_time
     *
     * @return the value of goods.end_time
     *
     * @mbggenerated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.end_time
     *
     * @param endTime the value for goods.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.commet_num
     *
     * @return the value of goods.commet_num
     *
     * @mbggenerated
     */
    public Integer getCommetNum() {
        return commetNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.commet_num
     *
     * @param commetNum the value for goods.commet_num
     *
     * @mbggenerated
     */
    public void setCommetNum(Integer commetNum) {
        this.commetNum = commetNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.phone_number
     *
     * @return the value of goods.phone_number
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.phone_number
     *
     * @param phoneNumber the value for goods.phone_number
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.qq_number
     *
     * @return the value of goods.qq_number
     *
     * @mbggenerated
     */
    public String getQqNumber() {
        return qqNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.qq_number
     *
     * @param qqNumber the value for goods.qq_number
     *
     * @mbggenerated
     */
    public void setQqNumber(String qqNumber) {
        this.qqNumber = qqNumber == null ? null : qqNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.wx_number
     *
     * @return the value of goods.wx_number
     *
     * @mbggenerated
     */
    public String getWxNumber() {
        return wxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.wx_number
     *
     * @param wxNumber the value for goods.wx_number
     *
     * @mbggenerated
     */
    public void setWxNumber(String wxNumber) {
        this.wxNumber = wxNumber == null ? null : wxNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.good_city
     *
     * @return the value of goods.good_city
     *
     * @mbggenerated
     */
    public String getGoodCity() {
        return goodCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.good_city
     *
     * @param goodCity the value for goods.good_city
     *
     * @mbggenerated
     */
    public void setGoodCity(String goodCity) {
        this.goodCity = goodCity == null ? null : goodCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.good_buy_method
     *
     * @return the value of goods.good_buy_method
     *
     * @mbggenerated
     */
    public String getGoodBuyMethod() {
        return goodBuyMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.good_buy_method
     *
     * @param goodBuyMethod the value for goods.good_buy_method
     *
     * @mbggenerated
     */
    public void setGoodBuyMethod(String goodBuyMethod) {
        this.goodBuyMethod = goodBuyMethod == null ? null : goodBuyMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.good_address
     *
     * @return the value of goods.good_address
     *
     * @mbggenerated
     */
    public String getGoodAddress() {
        return goodAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.good_address
     *
     * @param goodAddress the value for goods.good_address
     *
     * @mbggenerated
     */
    public void setGoodAddress(String goodAddress) {
        this.goodAddress = goodAddress == null ? null : goodAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.viewCount
     *
     * @return the value of goods.viewCount
     *
     * @mbggenerated
     */
    public Integer getViewcount() {
        return viewcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.viewCount
     *
     * @param viewcount the value for goods.viewCount
     *
     * @mbggenerated
     */
    public void setViewcount(Integer viewcount) {
        this.viewcount = viewcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.describle
     *
     * @return the value of goods.describle
     *
     * @mbggenerated
     */
    public String getDescrible() {
        return describle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.describle
     *
     * @param describle the value for goods.describle
     *
     * @mbggenerated
     */
    public void setDescrible(String describle) {
        this.describle = describle == null ? null : describle.trim();
    }


    public Byte getStatus() {
        return status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }
}