package com.springmvc.pojo;

public class Wanted {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wanted.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wanted.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wanted.good_id
     *
     * @mbggenerated
     */
    private Integer goodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wanted.create_at
     *
     * @mbggenerated
     */
    private String createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wanted
     *
     * @mbggenerated
     */
    public Wanted(Integer id, Integer userId, Integer goodId, String createAt) {
        this.id = id;
        this.userId = userId;
        this.goodId = goodId;
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wanted
     *
     * @mbggenerated
     */
    public Wanted() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wanted.id
     *
     * @return the value of wanted.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wanted.id
     *
     * @param id the value for wanted.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wanted.user_id
     *
     * @return the value of wanted.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wanted.user_id
     *
     * @param userId the value for wanted.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wanted.good_id
     *
     * @return the value of wanted.good_id
     *
     * @mbggenerated
     */
    public Integer getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wanted.good_id
     *
     * @param goodId the value for wanted.good_id
     *
     * @mbggenerated
     */
    public void setGoodId(Integer goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wanted.create_at
     *
     * @return the value of wanted.create_at
     *
     * @mbggenerated
     */
    public String getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wanted.create_at
     *
     * @param createAt the value for wanted.create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(String createAt) {
        this.createAt = createAt == null ? null : createAt.trim();
    }
}