package com.springmvc.dao;

import com.springmvc.pojo.Wanted;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WantedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wanted
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wanted
     *
     * @mbggenerated
     */
    int insert(Wanted record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wanted
     *
     * @mbggenerated
     */
    Wanted selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wanted
     *
     * @mbggenerated
     */
    List<Wanted> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wanted
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Wanted record);

    Wanted selectWant(@Param("uid") Integer uid, @Param("gid") Integer gid);

    List<Wanted> selectWantByUserId(@Param("uid") Integer uid);

    int deleteWantedByGoodsId(@Param("gid") Integer gid);
}